name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: ["3.10","3.11"]
  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v3
    with:
     python-version: ${{ matrix.python-version }}
  - run: pip install flake8
  - run: pip install mypy
  - run: flake8 run.py roop
  - run: mypy run.py roop
 test:
  strategy:
   matrix:
    os: [macos-latest, ubuntu-latest, windows-latest]
    python-version: ["3.10","3.11"]
  runs-on: ${{ matrix.os }}
  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Set up ffmpeg
    uses: FedericoCarboni/setup-ffmpeg@v2
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v3
    with:
     python-version: ${{ matrix.python-version }}
  - run: pip install -e .
  - run: roop-cli -s .github/examples/source.jpg -t .github/examples/target.mp4 -o .github/examples/output.mp4
    if: matrix.os != 'windows-latest'
  - run: roop-cli -s .github\examples\source.jpg -t .github\examples\target.mp4 -o .github\examples\output.mp4
    if: matrix.os == 'windows-latest'
  - run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -
    if: matrix.os != 'windows-latest'
  - run: ffmpeg -i .github\examples\snapshot.mp4 -i .github\examples\output.mp4 -filter_complex psnr -f null -
    if: matrix.os == 'windows-latest'

